# Generated by Django 6.0.2 on 2026-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome/Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('eh_solicitante', models.BooleanField(default=False)),
                ('eh_cliente', models.BooleanField(default=True)),
            ],
        ),
    ]
