# Generated by Django 6.0.2 on 2026-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
