# Generated by Django 6.0.2 on 2026-02-10 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_entidade_cpf_cnpj'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_entrada',
        ),
        migrations.AddField(
            model_name='amostra',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amostras', to='servicos.ordemservico'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_cliente', to='entidades.entidade'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_solicitadas', to='entidades.entidade'),
        ),
    ]
